{% set version = "3.1.1" %}

package:
  name: palettable
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/palettable/palettable-{{ version }}.tar.gz
  sha256: 0685b223a236bb7e2a900ef7a855ccf9a4027361c8acf400f3b350ea51870f80

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - palettable
    - palettable.cmocean
    - palettable.colorbrewer
    - palettable.cubehelix
    - palettable.matplotlib
    - palettable.mycarta
    - palettable.tableau
    - palettable.wesanderson

about:
  home: https://jiffyclub.github.io/palettable/
  license: MIT
  summary: 'Color palettes for Python.'

extra:
  recipe-maintainers:
    - ocefpaf
