{% set version = "3.0.0" %}

package:
  name: palettable
  version: {{ version }}

source:
  fn: palettable-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/palettable/palettable-{{ version }}.tar.gz
  sha256: eed9eb0399386ff42f90ca61d4fa38a1819a93d5adfc2d546e3e2869d9972c31

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - palettable
    - palettable.cmocean
    - palettable.colorbrewer
    - palettable.cubehelix
    - palettable.matplotlib
    - palettable.mycarta
    - palettable.tableau
    - palettable.wesanderson

about:
  home: https://jiffyclub.github.io/palettable/
  license: MIT
  summary: 'Color palettes for Python.'

extra:
  recipe-maintainers:
    - ocefpaf
