{% set version = "3.3.0" %}

package:
  name: palettable
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/palettable/palettable-{{ version }}.tar.gz
  sha256: 72feca71cf7d79830cd6d9181b02edf227b867d503bec953cf9fa91bf44896bd

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - palettable
    - palettable.cmocean
    - palettable.colorbrewer
    - palettable.cubehelix
    - palettable.matplotlib
    - palettable.mycarta
    - palettable.tableau
    - palettable.wesanderson

about:
  home: https://jiffyclub.github.io/palettable/
  license: MIT
  license_file: license.txt
  summary: 'Color palettes for Python.'

extra:
  recipe-maintainers:
    - ocefpaf
