travis:
  secure:
    BINSTAR_TOKEN: O1rRgEDOQV6qbG2/4m3uP4XiMvvw5hrutux4z3hUmomxTv9HCzVhAALkzLEmG4wYth45/IP0rDPQsgrPrbFRw+4kLPrjAsLn0rUffer4JZRDYRdYWaA8snUw8pVBEGTSApYmv5RFGhdvz60w77K+KKhdpdbvULNDky99z0UV3nI0abOvWfDUpTWXD2ejBhNXL1Ar//yIPaD0yyK1Kax8GmrezEt1DVSfvqf+RE52zyQ84Dvmckn/lS3WE3lw7BF+01VpxLHkGdDXimx5AiKwLXdnuyWS8viHGiHsnLcGmd6irkqP7yD6Lgxd40q93QA8Jb0erhocLpv+GAktIw7sHZ5NNea5CfDXmL3f3Ljz6h5D5AeaDyY2vsP/vLFWWfTE0AD9QaQDcAjwDZ2f0OERdFj7W06LqVMfJ466q+Ss78/naX3uTPIygiciRMnDj3i5PAEfp7kozmWhiP9wzIpCLXBlUZMGtyK9QvVYd4O4w/D/u6SshOvoCmfDK1B4wQXEC5VUIPr/1E/OtvaseDiU6xDodn88DpJv3t5YA9aKr8W6/wnWwVLp8E4ecsSV5e7Ces9OmhYdcH87LyPNi+jm9ijp7cFqWYApWyvvhAlz6kmcWCHw4uMk8lbAL4wVES8hHYhegZth9YwBrESF06nyjR1NWUzyeuVytbH7tfs57YI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
