travis:
  secure:
    BINSTAR_TOKEN: giHmvaxDyF+Xdcnh6UeDI+vdzh75oVlVd9m1GNeP+dHneJXU2xQRfrG/Dhh3xLlAqKQfjjIjFn0oyYWtAPoKpFaQ2DL8xut/n7kIBudlu80e8mCUowxRunDooG9ObXGjdD7hIoe/Flb0AUZc334XK2Z1CrroFEtRUQWBfaufphEY3jiCwhxRoSO3Su31J6amJfiJKCD9CShacmEKbWwOenh5OROBsw0GFHY8BQ/eL8ty4c8xALpNYCDDNqCJmQgt/Siqq0d8a7t4XlO1iwx+WHU17gMQCg5Kk2051nfpxX4JTu/UOA2g3wbVPIU27FSdKOV/qz1mE5eBxLs/L4bm4lkok6F8ft0mLF0wjEwX0kQufrTFjKQJODBKCKV+4cmA+d7aFsO9fsfwia4wXfFKnW9QOPBvsJIpM/oTzxwXGeUKbUXfziVe1whuoudcGWEEj2Y4AlGRwxm1uTYOmovNlb6PgX3bgGoYfbbwzWmSuMDwJJ8mTQtoFSuAAvBUf+HYXzd4wf73sM7qKh4hlE23j8ZAoZa3b+QbhWwrIuf7IOBPV+J5diITlFiKe46p4QlNZZJMggs32kVlTeqWnk8sRf3VBo4M4bDJdRScILp7TB7KLn6Lz8HTI4e1m04EbVapD9PJ+uotHXsT0IJMZHNE9TrolnEd+d6BigNA4UdkDNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
